name: "check-bigflow"
description: "Automating check after code changes"
author: chi

inputs:
  bf_start_time: 
    description: "The date that metrics should be calculated for"      
    required: true
    default: "NOW"
  bf_workflow_id: 
    description: "Workflow that should be run"    
    required: true
    default: "ALL"

runs:
  using: "composite"
  steps:
    - run: pip install -r resources/requirements.txt
      shell: bash

    - run: echo bf build --start-time ${{inputs.bf_start_time}} --workflow ${{inputs.bf_workflow_id}}
      shell: bash
      
    - run: bf build --start-time ${{inputs.bf_start_time}} --workflow ${{inputs.bf_workflow_id}}
      shell: bash

branding:
  icon: refresh-cw
  color: green
