name: "deploy-bigflow"
description: "Automating build after code changes"
author: chi

inputs:
  bf_env: 
    description: "Deployment environment"      
    required: true
    default: "dev"
  bf_vault_secret:
    description: "Vault secret"
    required: true
    
runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/deploy.sh
      shell: bash 
      
    - run: export bf_env = ${{ inputs.bf_env }}
      shell: bash
      
    - run: $GITHUB_ACTION_PATH/deploy.sh ${{inputs.bf_vault_secret}}
      shell: bash
    
branding:
  icon: refresh-cw
  color: green
