name: "build-bigflow"
description: "Automating build and release after code changes"
author: chi

inputs:
  bf_start_time: 
    description: "The date that metrics should be calculated for"      
    required: true
    default: "NOW"
  bf_workflow_id: 
    description: "Workflow that should be run"    
    required: true
    default: "ALL"
  repository_url: 
    description: "Repository URL"    
    required: true

runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/build.sh
      shell: bash
      
    - run: $GITHUB_ACTION_PATH/build.sh ${{inputs.repository_url}} ${{inputs.bf_start_time}} ${{inputs.bf_workflow_id}}
      shell: bash
    
    - run: chmod +rx variables.txt
      shell: bash

    - run: cp $GITHUB_ACTION_PATH/bamboo_build.py ./bamboo_build.py
      shell: bash

    - run: chmod +rx bamboo_build.py
      shell: bash
      
    - run: while read line; do export $line; done < variables.txt
      shell: bash
      
branding:
  icon: refresh-cw
  color: green
