name: "setup-bigflow"
description: "Automating build after code changes"
author: chi

inputs:
  release_sshkey:  # id of input
    description: 'Release key'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: install virtualenv
      run: pip3 install virtualenv
      shell: bash

    - name: clone bigflow scripts
      run: git clone https://stash.allegrogroup.com/scm/experimentschi/bigflow-template-scripts_tool_.git
      shell: bash

    - name: clone bigflow scripts
      run: cp bigflow-template-scripts_tool_/* .
      shell: bash

    - name: clone bigflow scripts
      run: chmod +rx build.sh
      shell: bash

    - name: clone bigflow scripts
      run: chmod +rx deploy.sh
      shell: bash

    - name: copy release key
      run: echo ${{inputs.release_sshkey}} > repositoryKey.pem
      shell: bash

    - name: change permissions
      run: chmod og-r repositoryKey.pem
      shell: bash

branding:
  icon: refresh-cw
  color: green
