name: "setup-bigflow"
description: "Automating build after code changes"
author: chi

inputs:
  release_sshkey:  # id of input
    description: 'Release key'
    required: true

runs:
  using: "composite"
  defaults:
      run:
        shell: bash
  steps:
    - name: install virtualenv
      run: pip3 install virtualenv

    - name: clone bigflow scripts
      run: git clone https://stash.allegrogroup.com/scm/experimentschi/bigflow-template-scripts_tool_.git

    - name: clone bigflow scripts
      run: cp bigflow-template-scripts_tool_/* .

    - name: clone bigflow scripts
      run: chmod +rx build.sh

    - name: clone bigflow scripts
      run: chmod +rx deploy.sh

    - name: copy release key
      run: echo ${{inputs.release_sshkey}} > repositoryKey.pem

    - name: change permissions
      run: chmod og-r repositoryKey.pem

branding:
  icon: refresh-cw
  color: green
